# This is a basic workflow to help you get started with Actions

name: CI_CD_MAIN

# Controls when the workflow will run
on:
  [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Instalacion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Instalacion de dependencias
        run: yarn install

      - name: Revision de codigo
        run: yarn install

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      # installs dependencies
      - name: Instalacion de dependencias
        run: yarn install

      # builds project
      - name: Compilacion del proyecto
        run: yarn build
   



  


